import {
  ProductsPage,
  NotificationsPage,
  SearchPage,
  ProductPage,
  CartPage,
  PaymentPage,
  OrderPage,
  ChoosePlacePage,
  OrderedPage,
  ProfilePage,
  ResetPasswordPage,
  PersonalDatePage,
  SettingsPage,
  HelpCenterPage,
  ExtraCardPage,
  AddNewCardPage,
  SignInPage,
  SignUpPage,
  ForgotPasswordPage,
  MyOrdersPage,
  MyOrderPage,
  MyOrdersSortedPage,
  StaffProfilePage,
  DashboardPage,
  IncomesPage,
  OrdersPage,
  FoodsListPage,
  CustomersListPage,
  UserPage,
  EmployersListPage,
  EmployerPage,
  FoodPage,
} from "@/pages";

export const routes = {
  public: [
    { path: "/", element: <ProductsPage /> },
    { path: "/notifications", element: <NotificationsPage /> },
    { path: "/search", element: <SearchPage /> },
    { path: "/products/:id", element: <ProductPage /> },
    { path: "/cart", element: <CartPage /> },
    { path: "/payment", element: <PaymentPage /> },
    { path: "/order/:id", element: <OrderPage /> },
    { path: "/choose-place", element: <ChoosePlacePage /> },
    { path: "/ordered", element: <OrderedPage /> },
    { path: "/profile", element: <ProfilePage /> },
    { path: "/reset-password", element: <ResetPasswordPage /> },
    { path: "/profile/personal-date", element: <PersonalDatePage /> },
    { path: "/profile/settings", element: <SettingsPage /> },
    { path: "/profile/help-center", element: <HelpCenterPage /> },
    { path: "/profile/extra-card", element: <ExtraCardPage /> },
    { path: "/profile/extra-card/new", element: <AddNewCardPage /> },
  ],
  auth: [
    { path: "/sign-in", element: <SignInPage /> },
    { path: "/sign-up", element: <SignUpPage /> },
    { path: "/sign-in/forgot-password", element: <ForgotPasswordPage /> },
  ],
  staff: [
    { path: "/staff/my-orders", element: <MyOrdersPage /> },
    { path: "/staff/my-order/:id", element: <MyOrderPage /> },
    { path: "/staff/my-orders/:type", element: <MyOrdersSortedPage /> },
    { path: "/staff/profile", element: <StaffProfilePage /> },
  ],
  admin: [
    { path: "/admin/dashboard", element: <DashboardPage /> },
    { path: "/admin/income", element: <IncomesPage /> },
    { path: "/admin/orders", element: <OrdersPage /> },
    { path: "/admin/foods", element: <FoodsListPage /> },
    { path: "/admin/customers", element: <CustomersListPage /> },
    { path: "/admin/employes", element: <EmployersListPage /> },
    { path: "/user/:id", element: <UserPage /> },
    { path: "/employer/:id", element: <EmployerPage /> },
    { path: "/foods/:id", element: <FoodPage /> },
  ],
};
